export const NEIGHBOURHOOD_NAME = 'Unity Court';
export const COMMUNITY_HALL_LAYOUT = Object.freeze({
  id: 'community-hall',
  name: 'Unity Community Hall',
  x: 10,
  z: 34,
  facing: 0,
  width: 6.6,
  depth: 5.4,
  halfX: 3.4,
  halfZ: 2.8,
  height: 4.6,
});
export const ESTATE_HOUSE_SIZE = Object.freeze({ width: 8.2, depth: 8.2 });
export const ESTATE_HOUSE_COLLISION_MARGIN = 0.22;

export const ESTATE_HOUSE_LAYOUT = Object.freeze([
  Object.freeze({ number: 1, x: 18, z: 1, facing: -Math.PI / 2 }),
  Object.freeze({ number: 2, x: 18, z: 17, facing: -Math.PI / 2 }),
  Object.freeze({ number: 3, x: 36, z: 1, facing: Math.PI / 2 }),
  Object.freeze({ number: 4, x: 36, z: 17, facing: Math.PI / 2 }),
]);

export const COMMERCE_VENUE_SIZE = Object.freeze({ width: 8.2, depth: 6.4 });
export const COMMERCE_VENUE_COLLIDER = Object.freeze({
  localX: 0,
  localZ: -0.33,
  halfX: 4.36,
  halfZ: 3.78,
  height: 5.7,
});

export const COMMERCE_VENUE_LAYOUT = Object.freeze([
  Object.freeze({
    id: 'cafe',
    kind: 'cafe',
    name: 'Civic Café',
    sign: 'CIVIC CAFE',
    x: 29,
    z: 33,
    facing: -Math.PI / 2,
    width: COMMERCE_VENUE_SIZE.width,
    depth: COMMERCE_VENUE_SIZE.depth,
    collider: COMMERCE_VENUE_COLLIDER,
    wallColor: 0xe8dcc8,
    roofColor: 0x526f5d,
    awningColor: 0x986849,
  }),
  Object.freeze({
    id: 'market',
    kind: 'mall',
    name: 'Unity Mall',
    sign: 'UNITY GRAND MALL',
    x: 61.2,
    z: 36.6,
    facing: Math.PI / 2,
    width: 21.6,
    depth: 13.6,
    collider: Object.freeze({
      localX: 0,
      localZ: -0.2,
      halfX: 11.0,
      halfZ: 7.0,
      height: 9.6,
    }),
    wallColor: 0xebe5d5,
    roofColor: 0x456b5c,
    awningColor: 0x3f7a63,
  }),
]);

export const MALL_SHOP_BAY_LAYOUT = Object.freeze([
  Object.freeze({
    spaceId: 'kiosk-s1',
    code: 'K1',
    sizeLabel: 'SMALL',
    localX: -8.1,
    localZ: -6.0,
    bayWidth: 3.3,
    bayHeight: 3.35,
    accentColor: 0xc97b49,
    pedestalOffsets: Object.freeze([[-0.65, 0], [0.65, 0]]),
  }),
  Object.freeze({
    spaceId: 'boutique-m2',
    code: 'B2',
    sizeLabel: 'MEDIUM',
    localX: -3.8,
    localZ: -6.8,
    bayWidth: 4.3,
    bayHeight: 3.95,
    accentColor: 0x3f7a63,
    pedestalOffsets: Object.freeze([[-1.1, 0.06], [0, -0.06], [1.1, 0.06]]),
  }),
  Object.freeze({
    spaceId: 'anchor-xl4',
    code: 'A4',
    sizeLabel: 'ANCHOR',
    localX: 1.5,
    localZ: -6.8,
    bayWidth: 5.4,
    bayHeight: 6.2,
    accentColor: 0x2f5e76,
    pedestalOffsets: Object.freeze([
      [-1.65, 0.1],
      [-0.98, -0.1],
      [-0.32, 0.1],
      [0.32, -0.1],
      [0.98, 0.1],
      [1.65, -0.1],
    ]),
  }),
  Object.freeze({
    spaceId: 'showroom-l3',
    code: 'S3',
    sizeLabel: 'LARGE',
    localX: 7.2,
    localZ: -6.8,
    bayWidth: 4.7,
    bayHeight: 4.5,
    accentColor: 0x7b5c8e,
    pedestalOffsets: Object.freeze([[-1.38, 0.08], [-0.46, -0.08], [0.46, -0.08], [1.38, 0.08]]),
  }),
]);

export const BILLBOARD_LAYOUT = Object.freeze([
  Object.freeze({
    id: 'billboard-mall',
    code: 'BB-01',
    name: 'Unity Mall Junction Megaboard',
    corridor: 'Commerce Promenade & Rail Crossing',
    locationLabel: 'Unity Mall Approach',
    x: 52.8,
    z: 25.4,
    facing: -Math.PI * 0.72,
    boardWidth: 5.8,
    boardHeight: 2.9,
    towerHeight: 4.6,
    halfX: 1.4,
    halfZ: 0.75,
    dailyImpressions: 2800,
    leaseCost: 45,
    payoutPerCollection: 28,
    defaultAd: Object.freeze({
      badge: 'UNITY MALL · 4 STOREFRONT TIERS',
      headline: 'RENT YOUR 3D SHOP AT UNITY MALL',
      subline: 'Display Virtual Goods · Kiosk to Anchor Hall · East Promenade',
      cta: 'VISIT UNITY MALL',
      theme: 'emerald',
      campaignType: 'mall',
    }),
  }),
  Object.freeze({
    id: 'billboard-civic',
    code: 'BB-02',
    name: 'Governor’s Boulevard Spectacular',
    corridor: 'Unity Community Hall & Civic Café',
    locationLabel: 'Civic Boulevard North',
    x: 18.2,
    z: 31.8,
    facing: Math.PI,
    boardWidth: 5.4,
    boardHeight: 2.7,
    towerHeight: 4.4,
    halfX: 1.3,
    halfZ: 0.7,
    dailyImpressions: 2200,
    leaseCost: 36,
    payoutPerCollection: 22,
    defaultAd: Object.freeze({
      badge: 'CIVIC SEAT · UNITY COURT',
      headline: 'RUN FOR GOVERNOR AT COMMUNITY HALL',
      subline: 'Hold Town Halls · Enact Policies · Fund Public Works',
      cta: 'OPEN GOVERNOR APP',
      theme: 'gold',
      campaignType: 'civic',
    }),
  }),
  Object.freeze({
    id: 'billboard-estate',
    code: 'BB-03',
    name: 'Unity Court Transit Gateway Board',
    corridor: 'Unity Court Avenue & Homes Hub',
    locationLabel: 'Unity Court Boulevard',
    x: 27.2,
    z: 12.6,
    facing: Math.PI,
    boardWidth: 5.4,
    boardHeight: 2.7,
    towerHeight: 4.4,
    halfX: 1.3,
    halfZ: 0.7,
    dailyImpressions: 2400,
    leaseCost: 38,
    payoutPerCollection: 24,
    defaultAd: Object.freeze({
      badge: 'UNITY COURT · FURNISHED HOMES',
      headline: 'LEASE A COTTAGE AT UNITY COURT',
      subline: 'Houses 01–04 · Local Landlords · Steps from Rail & Bus',
      cta: 'BROWSE HOMES APP',
      theme: 'terracotta',
      campaignType: 'brand',
    }),
  }),
  Object.freeze({
    id: 'billboard-circle',
    code: 'BB-04',
    name: 'Unity Circle Monumental Unipole',
    corridor: 'Unity Circle Plaza & South Transit Hub',
    locationLabel: 'Unity Circle Overlook',
    x: 16.5,
    z: -31.5,
    facing: -Math.PI * 0.72,
    boardWidth: 5.8,
    boardHeight: 2.85,
    towerHeight: 4.6,
    halfX: 1.35,
    halfZ: 0.72,
    dailyImpressions: 2600,
    leaseCost: 42,
    payoutPerCollection: 26,
    defaultAd: Object.freeze({
      badge: 'ABUJA TRANSIT · RAIL & BUS',
      headline: 'RIDE ABUJA CITY RAIL & SHUTTLE',
      subline: 'Connecting Unity Court, Unity Circle & Community Stadium',
      cta: 'BOARD AT ANY HUB',
      theme: 'royal',
      campaignType: 'brand',
    }),
  }),
  Object.freeze({
    id: 'billboard-stadium',
    code: 'BB-05',
    name: 'Abuja Stadium Matchday Megaboard',
    corridor: 'Abuja Community Stadium & West Hub',
    locationLabel: 'Stadium Concourse Approach',
    x: -46.8,
    z: 16.2,
    facing: -Math.PI * 0.42,
    boardWidth: 6.2,
    boardHeight: 3.0,
    towerHeight: 4.8,
    halfX: 1.45,
    halfZ: 0.78,
    dailyImpressions: 3200,
    leaseCost: 52,
    payoutPerCollection: 32,
    defaultAd: Object.freeze({
      badge: 'LIVE MATCHDAY · FLOODLIGHT ARENA',
      headline: 'CAPITAL STARS VS SAVANNAH UNITED',
      subline: 'Watch Live Broadcast View at Abuja Community Stadium',
      cta: 'WATCH MATCH LIVE',
      theme: 'sunset',
      campaignType: 'brand',
    }),
  }),
]);

